### PR TITLE
Calendar

### LINKED ISSUE #133: Calendar functionality
We want to be able to show upcoming events on the page. The calendar should:
- Show events
- Make distinction between ff-community events and other events related to that topic
- Offer subscription option (e.g. iCal)
- Allow to enter regular events

### PR DESCRIPTION
**Pull request by noxilixon**
My solution is that we generate ical feeds with hugo that are consumed and displayed by a js calendar. So we have a nice overview on the website and people can subscribe to the feed iif they want. New events are added like other content with a simple md file.

- [x] Add recurring events functionality in ical
- [x] style the events page
- [x] create englisch version of events page
- [x] Manage JS dependencies
- [x] Display [recurring events in words](https://github.com/jkbrzt/rrule)
- [x] Fix linting
- [ ] ~Separate feeds for `community`, `installation` and `external` events~
- [x] Write Readme

This resolves #133

### CODE REVIEW

**Comment by noxilixon** [comment]
> This is a link to a preview of the website from this Pull Request: [dev.berlin.freifunk.net/calendar/](http://dev.berlin.freifunk.net/calendar/).

Calender demo at http://dev.berlin.freifunk.net/calendar/events

**Comment by noxilixon** [comment]
Preview: https://freifunk.dev/calendar/

**Comment by noxilixon** [comment]
I will change the event box color, so that it fulfills the accessibility criteria. Do you have other feedback on look/feel and features?

**Comment by noxilixon** [comment]
Also I would squash the commits before merging.

**Comment by Noki** [comment]
the preview URL is just showing a 404.

**Comment by noxilixon** [comment]
> the preview URL is just showing a 404.

Ah sorry, forgot about that, i fixed the link

**Comment by Noki** [comment]
The line length is to high if you click an event. Should be reduced to the same width as the normal layout. 
The german page is in english (today, day names, time format) - can we change that?
I would also like to see at least one other event in the calender / feed.
In addition I find it kind of irritating that event names get shortened in the calendar.

**Comment by noxilixon** [comment]
I used rrules to define recurring events, because this is the standard in ical. I would keep it that way. Then I used the library [rrules](https://github.com/jkbrzt/rrule) to transform those rules into natural language. Works perfectly :smile:  ... but only for englisch :disappointed:. The library has [issues with translations](https://github.com/jkbrzt/rrule/issues/13). There is no good solution for that right now. So I will try to find a solution that is good enough.

**Comment by noxilixon** [comment]
I used rrules to define recurring events, because this is the standard in ical. I would keep it that way. Then I used the library [rrules](https://github.com/jkbrzt/rrule) to transform those rules into natural language. Works perfectly :smile:  ... but only for englisch :disappointed:. The library has [issues with translations](https://github.com/jkbrzt/rrule/issues/13). There is no good solution for that right now. I tried some of the solutions mentioned in the issue, but without a result that is acceptable "jedes Monat auf dem NaN Mittwoch" :laughing:. I introduced an additional variable to create the text manually.

**Review by Noki — CHANGES_REQUESTED** [review]
On Desktop I get a vertical scroll bar that breaks the layout:

image

From what I can see the calendar has a fixed limited height. This will be even worse with more events in different weeks of the same months or more events at the same day. Maybe add some more data for testing... ;-)

**Review by Noki — APPROVED** [review]
looks good to me now. squash this into a single commit and then feel free to merge.

**Pull request merged**
