### PR TITLE
add info@berlin.freifunk.net to impressum

### PR DESCRIPTION
**Pull request by andrenarchy**

### CODE REVIEW

**Comment by booo** [comment]
Is the mail address documented somewhere? Who has access and how can new members get access?

**Comment by andrenarchy** [comment]
No. What's the best place for documenting this?

**Comment by booo** [comment]
Maybe here http://wiki.freifunk.net/Berlin or here http://wiki.freifunk.net/Berlin:Server ?

**Comment by andrenarchy** [comment]
I added it to the latter wiki page.

**Comment by booo** [comment]
Thanks!

**Pull request merged**
