### PR TITLE
Apache: redirect homepage based on accept-language

### PR DESCRIPTION
**Pull request by Noki**

### CODE REVIEW

**Comment by nicolasberens** [comment]
If i understand this correctly, would this make it impossible to read the german page if your browser is set to english?

**Comment by Noki** [comment]
The functionality should be as follows: When a user accesses https://berlin.freifunk.net/ redirect him to either /de/ or /en/ based on the language accept header. Users can still manually switch the language, as this only affects that specific URL.

**Comment by nicolasberens** [comment]
ok.

(i haven't done any mod_rewrite in years and the `^/$` slipped my eyes)

**Review by nicolasberens — APPROVED** [review]

**Review by noxilixon — APPROVED** [review]

**Comment by noxilixon** [comment]
Tested on server. Is working as expected.

**Pull request merged**
